service: 
    name: schedule-example
provider:
 name: aws
 runtime: nodejs8.10
 memorySize: 128
 timeout: 10
 stage: production
 region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
       - kms:Decrypt
      Resource: { "Fn::Join" : ["", ["arn:aws:kms:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":key/662c685a-51e7-45a7-ad0d-478863112001" ] ]  }

functions:
    getFilesViaSFTP: 
        handler: index.handler
        events:
         - schedule:
            rate: cron(0 14 * * ? *)
            enabled: true
